# Default values for mychart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
operatorimage:
  repository: robinsys
  image: robin-operator
  tag: 5.3.2-64
  pullPolicy: IfNotPresent

robinimage:
  repository: robinsys
  image: robinimg
  tag: 5.3.2-64
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

k8sprovider:
  # supported values openshift,eks,gke,aks,iks,rke,upstream
  value: iks
host:
  # supported values physical,ec2,gcp,azure,ibm
  type: ibm


resources:
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #  cpu: 100m
  #  memory: 128Mi
  #requests:
  disks:
    count: 1
    size: 200

nodeSelector: {}

tolerations: []

